#
# mailhog permet d'intercepter les mails envoyés par prada et de les afficher dans une interface web
# très pratique pour le debug et ne pas avoir à envoyer de vrai mails
#

version: '3'

services:

  prada-web:
    environment:
      SMTP_TLS: "off"
      SMTP_HOST: "prada-mailhog"
      SMTP_PORT: "1025"
      SMTP_MAILDOMAIN: "abes.fr"

  # un serveur SMTP fictif permettant de debugguer les emails envoyés
  prada-mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: prada-mailhog
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    environment:
      MH_SMTP_BIND_ADDR: "0.0.0.0:1025" # cf https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md
    ports:
      - ${PRADA_MAILHOG_HTTP_PORT}:8025
      # 20231128: SGY port a retirer une fois la bascule realisee sur le reverse proxy
      - 9025:8025
    logging:
      driver: none # pas de log pour mailhog pour ne pas polluer le debug
